# HW 11 
# Задание 1
Написание тестов и их выполнение для keylist
```
-module(keylist_tests).
-author("kolpa").

-include_lib("eunit/include/eunit.hrl").

start_link_test() ->
  {ok, Pid} = keylist:start_link(test),
  ?assert(is_pid(Pid)),
  ?assertEqual(Pid, whereis(test)),
  keylist:stop(test),
  ?assertNot(is_process_alive(Pid)),
  ?debugFmt("Процессы запускаются, успешно!", []).

add_test() ->
  {ok, Pid} = keylist:start_link(test),
  ?assert(is_pid(Pid)),
  Key = key1,
  Value = value1,
  Comment = "Comment1",
  List = keylist:add(test, Key, Value, Comment),
  LengthList = length(List),
  ?assertEqual(1, LengthList),
  ?debugFmt("Записи добавляются, успешно!", []).


is_member_test() ->
  {ok, Pid} = keylist:start_link(test1),
  ?assert(is_pid(Pid)),
  Key = key1,
  Value = value1,
  Comment = "Comment1",
  keylist:add(test1, Key, Value, Comment),
  ?assertEqual(true, keylist:is_member(test1, Key)),
  ?debugFmt("Проверка на ключ, успешно!", []).

take_test() ->
  {ok, Pid} = keylist:start_link(test2),
  ?assert(is_pid(Pid)),
  Key = key1,
  Value = value1,
  Comment = "Comment1",
  List = keylist:add(test2, Key, Value, Comment),
  ?assertEqual(List, [keylist:take(test2, Key)]),
  ?debugFmt("Значения получаются, успешно!", []).

find_test() ->
  {ok, Pid} = keylist:start_link(test3),
  ?assert(is_pid(Pid)),
  Key = key1,
  Value = value1,
  Comment = "Comment1",
  keylist:add(test3, Key, Value, Comment),
  ?assertEqual({Key, Value, Comment}, keylist:find(test3, Key)),
  ?debugFmt("Записи ищются, успешно!", []).

delete_test() ->
  {ok, Pid} = keylist:start_link(test4),
  ?assert(is_pid(Pid)),
  Key = key1,
  Value = value1,
  Comment = "Comment1",
  keylist:add(test4, Key, Value, Comment),
  keylist:delete(test4, Key),
  ?assertEqual(false, keylist:is_member(test4, Key)),
  ?debugFmt("Записи удаляются успешно!", []).

stop_test() ->
  {ok, Pid} = keylist:start_link(test5),
  ?assert(is_pid(Pid)),
  keylist:stop(test5),
  ?assertEqual(undefined, whereis(test5)),
  ?debugFmt("Процессы останавливаются, успешно!", []).

```
# Result 
```
1> c(keylist_tests).
{ok,keylist_tests}
2> eunit:test(keylist_tests).
keylist_tests.erl:27:<0.104.0>: Процессы запускаются, успешно!
keylist_tests.erl:38:<0.104.0>: Записи добавляются, успешно!
keylist_tests.erl:49:<0.104.0>: Проверка на ключ, успешно!
keylist_tests.erl:59:<0.104.0>: Значения получаются, успешно!
keylist_tests.erl:69:<0.104.0>: Записи ищются, успешно!
keylist_tests.erl:80:<0.104.0>: Записи удаляются успешно!
keylist_tests.erl:87:<0.104.0>: Процессы останавливаются, успешно!
  All 7 tests passed.
ok
```
# Задание 2
В keylist_mgr в handle_info у вас должна осуществляться обработка ‘EXIT’ (для обработки завершения процессов которые были слинкованы с вашим keylist_mgr) и  ‘DOWN’ (для обработки завершения процессов которые мониторились вашим keylist_mgr)

```
handle_info({'DOWN', process, Pid}, State) ->
  #state{children=Children, permanent=Permanent} = State,
  case lists:keyfind(Pid, 2, Children) of
    {Name, _} ->
      %% Process with Name and Pid terminated, handle accordingly
      NewChildren = lists:keydelete(Name, 1, Children),
      NewPermanent = lists:keydelete(Pid, 1, Permanent),
      {noreply, State#state{children=NewChildren, permanent=NewPermanent}};
    false ->
      %% Process not found in children, handle accordingly
      {noreply, State}
  end;
```
# Задание 3

```
13> keylist_mgr:start().
{ok,<0.191.0>}
14> keylist_mgr:start_child(#{name => keylist1, restart => permanent}).
ChildList: []
ok
15> keylist_mgr:start_child(#{name => keylist2, restart => permanent}).
ChildList: [{keylist1,<0.193.0>}]
ok
16> keylist_mgr:start_child(#{name => keylist3, restart => temporary}).
ok
17> keylist_mgr:start_child(#{name => keylist4, restart => permanent}).
ChildList: [{keylist2,<0.195.0>},{keylist1,<0.193.0>}]
ok
exit(whereis(keylist1), kill).
true
=ERROR REPORT==== 27-Nov-2023::01:26:45.246000 ===
** Generic server keylist_mgr terminating
** Last message in was {'EXIT',<0.193.0>,killed}
** When Server state == {state,[{keylist4,<0.198.0>},
                                {keylist2,<0.195.0>},
                                {keylist1,<0.193.0>}],
                               [<0.198.0>,<0.195.0>,<0.193.0>]}
** Reason for termination ==
** {function_clause,[{proplists,get_value,
                                [restart,temporary,undefined],
                                [{file,"proplists.erl"},{line,216}]},
                     {keylist_mgr,handle_info,2,
                                  [{file,"keylist_mgr.erl"},{line,101}]},
                     {gen_server,try_handle_info,3,
                                 [{file,"gen_server.erl"},{line,1077}]},
                     {gen_server,handle_msg,6,
                                 [{file,"gen_server.erl"},{line,1165}]},
                     {proc_lib,init_p_do_apply,3,
                               [{file,"proc_lib.erl"},{line,241}]}]}

=CRASH REPORT==== 27-Nov-2023::01:26:45.247000 ===
  crasher:
    initial call: keylist_mgr:init/1
    pid: <0.191.0>
    registered_name: keylist_mgr
    exception error: no function clause matching
                     proplists:get_value(restart,temporary,undefined) (proplists.erl, line 216)
      in function  keylist_mgr:handle_info/2 (keylist_mgr.erl, line 101)
      in call from gen_server:try_handle_info/3 (gen_server.erl, line 1077)
      in call from gen_server:handle_msg/6 (gen_server.erl, line 1165)
    ancestors: [<0.155.0>,<0.154.0>,<0.153.0>,<0.65.0>,<0.69.0>,<0.64.0>,
                  kernel_sup,<0.47.0>]
    message_queue_len: 0
    messages: []
    links: [<0.195.0>,<0.198.0>,<0.155.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 610
    stack_size: 28
    reductions: 7410
  neighbours:
    neighbour:
      pid: <0.155.0>
      registered_name: []
      initial_call: {erlang,apply,2}
      current_function: {shell,eval_loop,4}
      ancestors: [<0.154.0>,<0.153.0>,<0.65.0>,<0.69.0>,<0.64.0>,kernel_sup,
                  <0.47.0>]
      message_queue_len: 0
      links: [<0.154.0>,<0.191.0>]
      trap_exit: false
      status: waiting
      heap_size: 2586
      stack_size: 8
      reductions: 45078
      current_stacktrace: [{shell,eval_loop,4,[{file,"shell.erl"},{line,717}]}]
    neighbour:
      pid: <0.198.0>
      registered_name: keylist4
      initial call: keylist:init/1
      current_function: {gen_server,loop,7}
      ancestors: [keylist_mgr,<0.155.0>,<0.154.0>,<0.153.0>,<0.65.0>,<0.69.0>,
                  <0.64.0>,kernel_sup,<0.47.0>]
      message_queue_len: 0
      links: [<0.191.0>]
      trap_exit: false
      status: waiting
      heap_size: 233
      stack_size: 11
      reductions: 41
      current_stacktrace: [{gen_server,loop,7,[{file,"gen_server.erl"},{line,983}]},
                  {proc_lib,init_p_do_apply,3,
                            [{file,"proc_lib.erl"},{line,241}]}]
    neighbour:
      pid: <0.195.0>
      registered_name: keylist2
      initial call: keylist:init/1
      current_function: {gen_server,loop,7}
      ancestors: [keylist_mgr,<0.155.0>,<0.154.0>,<0.153.0>,<0.65.0>,<0.69.0>,
                  <0.64.0>,kernel_sup,<0.47.0>]
      message_queue_len: 0
      links: [<0.191.0>]
      trap_exit: false
      status: waiting
      heap_size: 233
      stack_size: 11
      reductions: 58
      current_stacktrace: [{gen_server,loop,7,[{file,"gen_server.erl"},{line,983}]},
                  {proc_lib,init_p_do_apply,3,
                            [{file,"proc_lib.erl"},{line,241}]}]
** exception error: no function clause matching proplists:get_value(restart,temporary,undefined) (proplists
.erl, line 216)
     in function  keylist_mgr:handle_info/2 (keylist_mgr.erl, line 101)
     in call from gen_server:try_handle_info/3 (gen_server.erl, line 1077)
     in call from gen_server:handle_msg/6 (gen_server.erl, line 1165)
     in call from proc_lib:init_p_do_apply/3 (proc_lib.erl, line 241)
```

Из-за того, что не существует функционального предложения, соответствующего вызову proplists:get_value(restart, temporary, undefined). Из-за этого завершился не только дочерний, но и главный процесс

Следующая проверка
```
1> c(keylist).
keylist.erl:10:2: Warning: record key is unused
%   10| -record(key, {
%     |  ^

{ok,keylist}
2> keylist_mgr:start().
{ok,<0.92.0>}
3> keylist_mgr:start_child(#{name => keylist1, restart => permanent}).
ChildList: []
ok
4> keylist_mgr:start_child(#{name => keylist2, restart => permanent}).
ChildList: [{keylist1,<0.94.0>}]
ok
5> keylist:add(keylist1, key1, value1, "Comment1").
=ERROR REPORT==== 27-Nov-2023::01:35:33.291000 ===
** Generic server keylist_mgr terminating
** Last message in was {'EXIT',<0.85.0>,
                           {{timeout,
                                {gen_server,call,
                                    [keylist1,{add,key1,value1,"Comment1"}]}},
                            [{gen_server,call,2,
                                 [{file,"gen_server.erl"},{line,386}]},
                             {erl_eval,do_apply,7,
                                 [{file,"erl_eval.erl"},{line,750}]},
                             {shell,exprs,7,[{file,"shell.erl"},{line,782}]},
                             {shell,eval_exprs,7,
                                 [{file,"shell.erl"},{line,738}]},
                             {shell,eval_loop,4,
                                 [{file,"shell.erl"},{line,723}]}]}}
** When Server state == {state,[{keylist2,<0.96.0>},{keylist1,<0.94.0>}],
                               [<0.96.0>,<0.94.0>]}
** Reason for termination ==
** {{timeout,{gen_server,call,[keylist1,{add,key1,value1,"Comment1"}]}},
    [{gen_server,call,2,[{file,"gen_server.erl"},{line,386}]},
     {erl_eval,do_apply,7,[{file,"erl_eval.erl"},{line,750}]},
     {shell,exprs,7,[{file,"shell.erl"},{line,782}]},
     {shell,eval_exprs,7,[{file,"shell.erl"},{line,738}]},
     {shell,eval_loop,4,[{file,"shell.erl"},{line,723}]}]}

** exception exit: {timeout,{gen_server,call,
                                        [keylist1,{add,key1,value1,"Comment1"}]}}
     in function  gen_server:call/2 (gen_server.erl, line 386)
=CRASH REPORT==== 27-Nov-2023::01:35:33.292000 ===
  crasher:
    initial call: keylist_mgr:init/1
    pid: <0.92.0>
    registered_name: keylist_mgr
    exception exit: {{timeout,
                         {gen_server,call,
                             [keylist1,{add,key1,value1,"Comment1"}]}},
                     [{gen_server,call,2,[{file,"gen_server.erl"},{line,386}]},
                      {erl_eval,do_apply,7,[{file,"erl_eval.erl"},{line,750}]},
                      {shell,exprs,7,[{file,"shell.erl"},{line,782}]},
                      {shell,eval_exprs,7,[{file,"shell.erl"},{line,738}]},
                      {shell,eval_loop,4,[{file,"shell.erl"},{line,723}]}]}
      in function  gen_server:decode_msg/9 (gen_server.erl, line 1031)
    ancestors: [<0.85.0>,<0.84.0>,<0.70.0>,<0.65.0>,<0.69.0>,<0.64.0>,
                  kernel_sup,<0.47.0>]
    message_queue_len: 1
    messages: [{'EXIT',<0.85.0>,normal}]
    links: [<0.94.0>,<0.96.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 610
    stack_size: 28
    reductions: 11339
  neighbours:
    neighbour:
      pid: <0.96.0>
      registered_name: keylist2
      initial call: keylist:init/1
      current_function: {gen_server,loop,7}
      ancestors: [keylist_mgr,<0.85.0>,<0.84.0>,<0.70.0>,<0.65.0>,<0.69.0>,
                  <0.64.0>,kernel_sup,<0.47.0>]
      message_queue_len: 0
      links: [<0.92.0>]
      trap_exit: false
      status: waiting
      heap_size: 233
      stack_size: 11
      reductions: 41
      current_stacktrace: [{gen_server,loop,7,[{file,"gen_server.erl"},{line,983}]},
                  {proc_lib,init_p_do_apply,3,
                            [{file,"proc_lib.erl"},{line,241}]}]
    neighbour:
      pid: <0.94.0>
      registered_name: keylist1
      initial call: keylist:init/1
      current_function: {timer,sleep,1}
      ancestors: [keylist_mgr,<0.85.0>,<0.84.0>,<0.70.0>,<0.65.0>,<0.69.0>,
                  <0.64.0>,kernel_sup,<0.47.0>]
      message_queue_len: 0
      links: [<0.92.0>]
      trap_exit: false
      status: waiting
      heap_size: 233
      stack_size: 23
      reductions: 65
      current_stacktrace: [{timer,sleep,1,[{file,"timer.erl"},{line,235}]},
                  {keylist,handle_call,3,[{file,"keylist.erl"},{line,63}]},
                  {gen_server,try_handle_call,4,
                              [{file,"gen_server.erl"},{line,1113}]},
                  {gen_server,handle_msg,6,
                              [{file,"gen_server.erl"},{line,1142}]},
                  {proc_lib,init_p_do_apply,3,
                            [{file,"proc_lib.erl"},{line,241}]}]
6> whereis(keylist2).
undefined
```
# Что произошло? 
В данной ситуации расматривалась реакция основного процесса на нестандартную заддержку ответа сервера после выхова функции add. Основной как и дочерние завершились. Так как по умолчанию жидание не должно превышать 5000 мс.
# Как бы мы могли это исправить(Без удаления timer:sleep(10000))? Изменить дефолтное значение Timeout? 
При обращении к Api keylist что также реализованно с помощью gen_server можно передать 3 параметром значении тайм-аута, после которого процесс аварийно завершится.
```
gen_server:call(Name, {add, Key, Value, Comment}, 10000).
```
Следующая ситуация: 
```
2> c(keylist).
keylist.erl:10:2: Warning: record key is unused
%   10| -record(key, {
%     |  ^

keylist.erl:64:4: Warning: evaluation of operator '/'/2 will fail with a 'badarith' exception
%   64|   1/0,
%     |    ^

keylist.erl:64:4: Warning: the result of evaluating operator '/'/2 is ignored (suppress the warning by assi
gning the expression to the _ variable)
%   64|   1/0,
%     |    ^

{ok,keylist}
3> keylist_mgr:start().
{ok,<0.97.0>}
4> keylist_mgr:start_child(#{name => keylist1, restart => permanent}).
ChildList: []
ok
5> keylist_mgr:start_child(#{name => keylist2, restart => permanent}).
ChildList: [{keylist1,<0.99.0>}]
ok
6> keylist:add(keylist1, key1, value1, "Comment1").
=ERROR REPORT==== 27-Nov-2023::01:49:00.387000 ===
** Generic server keylist1 terminating
** Last message in was {add,key1,value1,"Comment1"}
** When Server state == []
** Reason for termination ==
** {badarith,[{keylist,handle_call,3,[{file,"keylist.erl"},{line,64}]},
              {gen_server,try_handle_call,4,
                          [{file,"gen_server.erl"},{line,1113}]},
              {gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,1142}]},
              {proc_lib,init_p_do_apply,3,
                        [{file,"proc_lib.erl"},{line,241}]}]}
** Client <0.85.0> stacktrace
** [{gen,do_call,4,[{file,"gen.erl"},{line,259}]},
    {gen_server,call,2,[{file,"gen_server.erl"},{line,382}]},
    {erl_eval,do_apply,7,[{file,"erl_eval.erl"},{line,750}]},
    {shell,exprs,7,[{file,"shell.erl"},{line,782}]},
    {shell,eval_exprs,7,[{file,"shell.erl"},{line,738}]},
    {shell,eval_loop,4,[{file,"shell.erl"},{line,723}]}]

=CRASH REPORT==== 27-Nov-2023::01:49:00.388000 ===
  crasher:
    initial call: keylist:init/1
    pid: <0.99.0>
    registered_name: keylist1
    exception error: an error occurred when evaluating an arithmetic expression
      in function  keylist:handle_call/3 (keylist.erl, line 64)
      in call from gen_server:try_handle_call/4 (gen_server.erl, line 1113)
      in call from gen_server:handle_msg/6 (gen_server.erl, line 1142)
    ancestors: [keylist_mgr,<0.85.0>,<0.84.0>,<0.70.0>,<0.65.0>,<0.69.0>,
                  <0.64.0>,kernel_sup,<0.47.0>]
    message_queue_len: 0
    messages: []
    links: [<0.97.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 376
    stack_size: 28
    reductions: 9017
  neighbours:

=ERROR REPORT==== 27-Nov-2023::01:49:00.390000 ===
** Generic server keylist_mgr terminating
** Last message in was {'EXIT',<0.99.0>,
                           {badarith,
                               [{keylist,handle_call,3,
                                    [{file,"keylist.erl"},{line,64}]},
                                {gen_server,try_handle_call,4,
                                    [{file,"gen_server.erl"},{line,1113}]},
                                {gen_server,handle_msg,6,
                                    [{file,"gen_server.erl"},{line,1142}]},
                                {proc_lib,init_p_do_apply,3,
                                    [{file,"proc_lib.erl"},{line,241}]}]}}
** When Server state == {state,[{keylist2,<0.101.0>},{keylist1,<0.99.0>}],
                               [<0.101.0>,<0.99.0>]}
** Reason for termination ==
** {function_clause,[{proplists,get_value,
                                [restart,temporary,undefined],
                                [{file,"proplists.erl"},{line,216}]},
                     {keylist_mgr,handle_info,2,
                                  [{file,"keylist_mgr.erl"},{line,101}]},
                     {gen_server,try_handle_info,3,
                                 [{file,"gen_server.erl"},{line,1077}]},
                     {gen_server,handle_msg,6,
                                 [{file,"gen_server.erl"},{line,1165}]},
                     {proc_lib,init_p_do_apply,3,
                               [{file,"proc_lib.erl"},{line,241}]}]}

** exception exit: {{badarith,[{keylist,handle_call,3,
                                        [{file,"keylist.erl"},{line,64}]},
                               {gen_server,try_handle_call,4,
                                           [{file,"gen_server.erl"},{line,1113}]},
                               {gen_server,handle_msg,6,
                                           [{file,"gen_server.erl"},{line,1142}]},
                               {proc_lib,init_p_do_apply,3,
                                         [{file,"proc_lib.erl"},{line,241}]}]},
                    {gen_server,call,[keylist1,{add,key1,value1,"Comment1"}]}}
     in function  gen_server:call/2 (gen_server.erl, line 386)
=CRASH REPORT==== 27-Nov-2023::01:49:00.390000 ===
  crasher:
    initial call: keylist_mgr:init/1
    pid: <0.97.0>
    registered_name: keylist_mgr
    exception error: no function clause matching
                     proplists:get_value(restart,temporary,undefined) (proplists.erl, line 216)
      in function  keylist_mgr:handle_info/2 (keylist_mgr.erl, line 101)
      in call from gen_server:try_handle_info/3 (gen_server.erl, line 1077)
      in call from gen_server:handle_msg/6 (gen_server.erl, line 1165)
    ancestors: [<0.85.0>,<0.84.0>,<0.70.0>,<0.65.0>,<0.69.0>,<0.64.0>,
                  kernel_sup,<0.47.0>]
    message_queue_len: 2
    messages: [{'EXIT',<0.85.0>,
                      {{{badarith,
                            [{keylist,handle_call,3,
                                 [{file,"keylist.erl"},{line,64}]},
                             {gen_server,try_handle_call,4,
                                 [{file,"gen_server.erl"},{line,1113}]},
                             {gen_server,handle_msg,6,
                                 [{file,"gen_server.erl"},{line,1142}]},
                             {proc_lib,init_p_do_apply,3,
                                 [{file,"proc_lib.erl"},{line,241}]}]},
                        {gen_server,call,
                            [keylist1,{add,key1,value1,"Comment1"}]}},
                       [{gen_server,call,2,
                            [{file,"gen_server.erl"},{line,386}]},
                        {erl_eval,do_apply,7,
                            [{file,"erl_eval.erl"},{line,750}]},
                        {shell,exprs,7,[{file,"shell.erl"},{line,782}]},
                        {shell,eval_exprs,7,[{file,"shell.erl"},{line,738}]},
                        {shell,eval_loop,4,[{file,"shell.erl"},{line,723}]}]}},
                  {'EXIT',<0.85.0>,normal}]
    links: [<0.101.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 610
    stack_size: 28
    reductions: 10234
  neighbours:
    neighbour:
      pid: <0.101.0>
      registered_name: keylist2
      initial call: keylist:init/1
      current_function: {gen_server,loop,7}
      ancestors: [keylist_mgr,<0.85.0>,<0.84.0>,<0.70.0>,<0.65.0>,<0.69.0>,
                  <0.64.0>,kernel_sup,<0.47.0>]
      message_queue_len: 0
      links: [<0.97.0>]
      trap_exit: false
      status: waiting
      heap_size: 233
      stack_size: 11
      reductions: 41
      current_stacktrace: [{gen_server,loop,7,[{file,"gen_server.erl"},{line,983}]},
                  {proc_lib,init_p_do_apply,3,
                            [{file,"proc_lib.erl"},{line,241}]}]

```
Как и в прошлом случае завершился главный и дочерний процесс так как при пропытке перезапустить keylist1 внось натыкался на ту же ошибку.

Рассматривая данную ситуацию под пругим углом, что в результате некоторых вычислений может возникнуть exception стоит выделять данные блоки кода в try catch.